# src/rankforge/schemas/game.py

"""Pydantic schemas for the Game resource."""

from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


# ===============================================
# Enums
# ===============================================
class RatingStrategy(str, Enum):
    """Valid rating calculation strategies."""

    GLICKO2 = "glicko2"
    DUMMY = "dummy"


def validate_rating_config(config: dict[str, Any]) -> dict[str, Any]:
    """Validate the known rating_config keys; unknown keys pass through.

    Known keys:
        min_swing: number >= 0 — guaranteed minimum rating gain on a win /
            drop on a loss (0/absent = pure Glicko-2)
        margin_weight_factor: number >= 0 — scales match weight by score margin
        score_preset: int >= 1 — typical winning score, used by quick entry UI
        leaderboard_mode: "rating" | "conservative"
        tau: number in (0, 3] — Glicko-2 system constant (default 0.5)
        season_rd_reset: number in [30, 500] — RD applied at season
            boundaries (default 350)
        rd_growth_period_days: number >= 0 — days per idle "rating period";
            a player's RD grows for time away (0/absent = off)
    """
    for key in ("min_swing", "margin_weight_factor", "rd_growth_period_days"):
        if key in config:
            value = config[key]
            if (
                isinstance(value, bool)
                or not isinstance(value, (int, float))
                or value < 0
            ):
                raise ValueError(f"{key} must be a non-negative number")
    if "tau" in config:
        value = config["tau"]
        if (
            isinstance(value, bool)
            or not isinstance(value, (int, float))
            or not (0 < value <= 3)
        ):
            raise ValueError("tau must be a number in (0, 3]")
    if "score_preset" in config:
        value = config["score_preset"]
        if isinstance(value, bool) or not isinstance(value, int) or value < 1:
            raise ValueError("score_preset must be a positive integer")
    if "leaderboard_mode" in config:
        if config["leaderboard_mode"] not in ("rating", "conservative"):
            raise ValueError("leaderboard_mode must be 'rating' or 'conservative'")
    if "season_rd_reset" in config:
        value = config["season_rd_reset"]
        if (
            isinstance(value, bool)
            or not isinstance(value, (int, float))
            or not (30 <= value <= 500)
        ):
            raise ValueError("season_rd_reset must be a number in [30, 500]")
    return config


# ===============================================
# Base Schema: Defines shared attributes
# ===============================================
class GameBase(BaseModel):
    """Shared attributes for a game."""

    name: str = Field(..., min_length=2, max_length=200)
    rating_strategy: RatingStrategy
    description: str | None = Field(None, max_length=1000)
    rating_config: dict[str, Any] = Field(default_factory=dict)

    _validate_config = field_validator("rating_config")(validate_rating_config)


# ===============================================
# Create Schema: Defines attributes for creation
# ===============================================
class GameCreate(GameBase):
    """Properties to receive via API on create."""

    # No extra fields needed for creation, inherits all from GameBase.
    pass


# ===============================================
# Update Schema: Defines attributes for updates
# ===============================================
class GameUpdate(BaseModel):
    """Properties to receive via API on update."""

    # When updating, all fields should be optional.
    name: str | None = Field(None, min_length=2, max_length=200)
    rating_strategy: RatingStrategy | None = None
    description: str | None = Field(None, max_length=1000)
    rating_config: dict[str, Any] | None = None

    @field_validator("rating_config")
    @classmethod
    def _validate_config(cls, v: dict[str, Any] | None) -> dict[str, Any] | None:
        return None if v is None else validate_rating_config(v)


# ===============================================
# Read Schema: Defines attributes for returning data
# ===============================================
class GameRead(GameBase):
    """Properties to return to the client."""

    # The 'id' is generated by the database, so it's only in the read model.
    id: int

    # This config allows Pydantic to read data from ORM models.
    # It tells Pydantic to access fields like `game.id` instead of `game['id']`.
    model_config = ConfigDict(from_attributes=True)


# ===============================================
# Season Schemas
# ===============================================
class SeasonRead(BaseModel):
    """A season boundary."""

    id: int
    game_id: int
    number: int
    started_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SeasonList(BaseModel):
    """A game's season boundaries plus its current season number.

    Season 1 is implicit (no row); ``current_season`` is 1 until the first
    boundary is created.
    """

    current_season: int
    items: list[SeasonRead]


# ===============================================
# Health Schema: rating-system drift monitoring
# ===============================================
class GameHealth(BaseModel):
    """Rating-system health metrics for a game.

    A zero-sum-ish rating system should keep its mean near the 1500 anchor;
    sustained drift signals inflation/deflation (e.g. from weighted matches
    or players entering/leaving at non-average skill).
    """

    game_id: int
    players: int
    matches: int
    mean_rating: float
    rating_drift: float = Field(description="Absolute distance of mean from 1500")
